export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const SET_PRODUCTS_DATA = "SET_PRODUCTS_DATA";
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const ERROR_GET_ALL_PRODUCTS = "ERROR_GET_ALL_PRODUCTS";
